// SPDX-License-Identifier: Apache-2.0
/**
 * Interactive environment bootstrap. Phase 3 / Phase 4 task.
 */

import { execSync } from "node:child_process";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as readline from "node:readline";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const cdkDir = join(__dirname, "..");
const repoRoot = join(__dirname, "..", "..", "..");

interface Args {
  env: string;
  region: string;
  callbackUrl?: string;
}

function parseArgs(): Args {
  const args = process.argv.slice(2);
  const get = (k: string, d?: string) => {
    const i = args.indexOf(`--${k}`);
    return i >= 0 ? args[i + 1] : d;
  };
  return {
    env: get("env", "dev")!,
    region: get("region", process.env.AWS_REGION ?? "us-east-1")!,
    callbackUrl: get("callback-url"),
  };
}

async function prompt(q: string, def?: string): Promise<string> {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(`${q}${def ? ` [${def}]` : ""}: `, (ans) => {
      rl.close();
      resolve(ans.trim() || def || "");
    });
  });
}

async function main(): Promise<void> {
  const args = parseArgs();
  const callback = args.callbackUrl ?? (await prompt("Callback URL", "http://localhost:5173/auth/callback"));
  const logoutUrl = callback.replace(/\/auth\/callback$/, "/");

  console.log(`Deploying YuiPathStack-${args.env} to ${args.region}...`);
  execSync(
    `pnpm cdk deploy YuiPathStack-${args.env} --require-approval never --outputs-file outputs-${args.env}.json --context envName=${args.env} --context region=${args.region} --context callbackUrl=${callback} --context logoutUrl=${logoutUrl}`,
    { cwd: cdkDir, stdio: "inherit" },
  );

  const outputs = JSON.parse(
    execSync(`cat outputs-${args.env}.json`, { cwd: cdkDir }).toString(),
  ) as Record<string, Record<string, string>>;
  const stack = outputs[`YuiPathStack-${args.env}`] ?? {};

  const envContent = [
    `# Generated by setup-env.ts; do not commit. Edit only via this script.`,
    `VITE_API_BASE=${stack.ApiEndpoint ?? ""}`,
    `VITE_COGNITO_USER_POOL_ID=${stack.UserPoolId ?? ""}`,
    `VITE_COGNITO_CLIENT_ID=${stack.WebClientId ?? ""}`,
    `VITE_COGNITO_HOSTED_UI=${stack.HostedUiUrl ?? ""}`,
    `VITE_CLOUDFRONT_DOMAIN=${stack.DistributionDomain ?? ""}`,
    "",
  ].join("\n");
  const webEnvDir = join(repoRoot, "apps", "web");
  mkdirSync(webEnvDir, { recursive: true });
  writeFileSync(join(webEnvDir, `.env.${args.env}`), envContent);
  console.log(`Wrote apps/web/.env.${args.env}`);

  console.log("Next steps:");
  console.log("  1. cd apps/web && VITE_BUILD_ENV=" + args.env + " pnpm build");
  console.log(`  2. aws s3 sync apps/web/dist s3://${stack.WebBucketName ?? "<bucket>"}/`);
  console.log(`  3. aws cloudfront create-invalidation --distribution-id <id> --paths "/*"`);
  console.log(
    "  4. Register apps/api/openapi.json with AgentCore Gateway via the AWS console or `agentcore-toolkit`.",
  );
}

main().catch((e: Error) => {
  console.error(e);
  process.exit(1);
});
