/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Healthz */
    get: operations["healthz_healthz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/readyz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readyz */
    get: operations["readyz_readyz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["me_api_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Projects */
    get: operations["list_projects_api_projects_get"];
    put?: never;
    /** Create Project */
    post: operations["create_project_api_projects_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Project */
    get: operations["get_project_api_projects__project_id__get"];
    put?: never;
    post?: never;
    /** Delete Project */
    delete: operations["delete_project_api_projects__project_id__delete"];
    options?: never;
    head?: never;
    /** Update Project */
    patch: operations["update_project_api_projects__project_id__patch"];
    trace?: never;
  };
  "/api/projects/{project_id}/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Tasks */
    get: operations["list_tasks_api_projects__project_id__tasks_get"];
    put?: never;
    /** Create Task */
    post: operations["create_task_api_projects__project_id__tasks_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/tasks/{task_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Task */
    get: operations["get_task_api_projects__project_id__tasks__task_id__get"];
    put?: never;
    post?: never;
    /** Delete Task */
    delete: operations["delete_task_api_projects__project_id__tasks__task_id__delete"];
    options?: never;
    head?: never;
    /** Update Task */
    patch: operations["update_task_api_projects__project_id__tasks__task_id__patch"];
    trace?: never;
  };
  "/api/projects/{project_id}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Members */
    get: operations["list_members_api_projects__project_id__members_get"];
    put?: never;
    /** Add Member */
    post: operations["add_member_api_projects__project_id__members_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/members/{user_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove Member */
    delete: operations["remove_member_api_projects__project_id__members__user_id__delete"];
    options?: never;
    head?: never;
    /** Update Member */
    patch: operations["update_member_api_projects__project_id__members__user_id__patch"];
    trace?: never;
  };
  "/api/projects/{project_id}/tasks/{task_id}/comments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Comments */
    get: operations["list_comments_api_projects__project_id__tasks__task_id__comments_get"];
    put?: never;
    /** Create Comment */
    post: operations["create_comment_api_projects__project_id__tasks__task_id__comments_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/tasks/{task_id}/comments/{comment_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Comment */
    delete: operations["delete_comment_api_projects__project_id__tasks__task_id__comments__comment_id__delete"];
    options?: never;
    head?: never;
    /** Update Comment */
    patch: operations["update_comment_api_projects__project_id__tasks__task_id__comments__comment_id__patch"];
    trace?: never;
  };
  "/api/calendar-templates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Calendars */
    get: operations["list_calendars_api_calendar_templates_get"];
    put?: never;
    /** Create Calendar */
    post: operations["create_calendar_api_calendar_templates_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/calendar-templates/{cal_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Calendar */
    get: operations["get_calendar_api_calendar_templates__cal_id__get"];
    put?: never;
    post?: never;
    /** Delete Calendar */
    delete: operations["delete_calendar_api_calendar_templates__cal_id__delete"];
    options?: never;
    head?: never;
    /** Update Calendar */
    patch: operations["update_calendar_api_calendar_templates__cal_id__patch"];
    trace?: never;
  };
  "/api/projects/{project_id}/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Project Events */
    get: operations["list_project_events_api_projects__project_id__events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/by-target": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Target Events */
    get: operations["list_target_events_api_events_by_target_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** CalendarCreateInput */
    CalendarCreateInput: {
      /** Name */
      name: string;
      /** Working Days */
      working_days?: boolean[] | null;
      /** Holidays */
      holidays?: components["schemas"]["Holiday"][];
    };
    /** CalendarTemplate */
    CalendarTemplate: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Working Days */
      working_days?: boolean[];
      /** Holidays */
      holidays?: components["schemas"]["Holiday"][];
      /**
       * Version
       * @default 0
       */
      version: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** CalendarUpdateInput */
    CalendarUpdateInput: {
      /** Name */
      name?: string | null;
      /** Working Days */
      working_days?: boolean[] | null;
      /** Holidays */
      holidays?: components["schemas"]["Holiday"][] | null;
      /** Expected Version */
      expected_version: number;
    };
    /** Comment */
    Comment: {
      /** Id */
      id: string;
      /** Task Id */
      task_id: string;
      /** Author Id */
      author_id: string;
      /** Body */
      body: string;
      /**
       * Version
       * @default 0
       */
      version: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** CommentCreateInput */
    CommentCreateInput: {
      /** Body */
      body: string;
    };
    /** CommentUpdateInput */
    CommentUpdateInput: {
      /** Body */
      body: string;
      /** Expected Version */
      expected_version: number;
    };
    /** Event */
    Event: {
      /** Id */
      id: string;
      /**
       * Ts
       * Format: date-time
       */
      ts: string;
      /** Actor */
      actor: string;
      /** Project Id */
      project_id: string;
      kind: components["schemas"]["EventKind"];
      target?: components["schemas"]["TargetRef"] | null;
      /** Payload */
      payload?: {
        [key: string]: unknown;
      };
    };
    /**
     * EventKind
     * @enum {string}
     */
    EventKind:
      | "task.created"
      | "task.updated"
      | "task.deleted"
      | "comment.created"
      | "comment.updated"
      | "comment.deleted"
      | "project.created"
      | "project.updated"
      | "project.deleted"
      | "member.added"
      | "member.removed"
      | "member.role_changed"
      | "calendar_template.created"
      | "calendar_template.updated"
      | "calendar_template.deleted"
      | "sensitive.read";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Holiday */
    Holiday: {
      /**
       * Date
       * Format: date
       */
      date: string;
      /**
       * Name
       * @default
       */
      name: string;
    };
    /** Membership */
    Membership: {
      /** User Id */
      user_id: string;
      /** Project Id */
      project_id: string;
      role: components["schemas"]["Role"];
      /**
       * Color
       * @default #94a3b8
       */
      color: string;
      /**
       * Capacity
       * @default 1
       */
      capacity: number;
      /**
       * Allocation
       * @default 1
       */
      allocation: number;
      /**
       * Joined At
       * Format: date-time
       */
      joined_at: string;
    };
    /** MembershipCreateInput */
    MembershipCreateInput: {
      /** User Id */
      user_id: string;
      role: components["schemas"]["Role"];
      /**
       * Color
       * @default #94a3b8
       */
      color: string;
      /**
       * Capacity
       * @default 1
       */
      capacity: number;
      /**
       * Allocation
       * @default 1
       */
      allocation: number;
    };
    /** MembershipUpdateInput */
    MembershipUpdateInput: {
      role?: components["schemas"]["Role"] | null;
      /** Color */
      color?: string | null;
      /** Capacity */
      capacity?: number | null;
      /** Allocation */
      allocation?: number | null;
      /** Expected Version */
      expected_version?: number | null;
    };
    /** Project */
    Project: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /**
       * Description
       * @default
       */
      description: string;
      /** Calendar Template Id */
      calendar_template_id?: string | null;
      /**
       * Version
       * @default 0
       */
      version: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ProjectCreateInput */
    ProjectCreateInput: {
      /** Name */
      name: string;
      /**
       * Description
       * @default
       */
      description: string;
      /** Calendar Template Id */
      calendar_template_id?: string | null;
    };
    /** ProjectUpdateInput */
    ProjectUpdateInput: {
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
      /** Calendar Template Id */
      calendar_template_id?: string | null;
      /**
       * Expected Version
       * @description optimistic locking; must match current version
       */
      expected_version: number;
    };
    /**
     * Role
     * @enum {string}
     */
    Role: "project_admin" | "project_member";
    /** TargetRef */
    TargetRef: {
      /** Type */
      type: string;
      /** Id */
      id: string;
    };
    /** Task */
    Task: {
      /** Id */
      id: string;
      /** Project Id */
      project_id: string;
      /** Name */
      name: string;
      /**
       * Description
       * @default
       */
      description: string;
      /** Parent */
      parent?: string | null;
      /**
       * Is Phase
       * @default false
       */
      is_phase: boolean;
      /**
       * Start
       * Format: date
       */
      start: string;
      /**
       * End
       * Format: date
       */
      end: string;
      /**
       * Duration
       * @description working days
       */
      duration: number;
      /** @default todo */
      status: components["schemas"]["TaskStatus"];
      /**
       * Progress
       * @default 0
       */
      progress: number;
      /** Owner */
      owner?: string | null;
      /** Subs */
      subs?: string[];
      /** Predecessors */
      predecessors?: string[];
      /**
       * Critical
       * @default false
       */
      critical: boolean;
      /**
       * Milestone
       * @default false
       */
      milestone: boolean;
      /**
       * Depth
       * @default 0
       */
      depth: number;
      /**
       * Version
       * @default 0
       */
      version: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** TaskCreateInput */
    TaskCreateInput: {
      /** Name */
      name: string;
      /**
       * Description
       * @default
       */
      description: string;
      /** Parent */
      parent?: string | null;
      /**
       * Is Phase
       * @default false
       */
      is_phase: boolean;
      /**
       * Start
       * Format: date
       */
      start: string;
      /**
       * End
       * Format: date
       */
      end: string;
      /** Duration */
      duration: number;
      /** @default todo */
      status: components["schemas"]["TaskStatus"];
      /** Progress */
      progress?: number | null;
      /** Owner */
      owner?: string | null;
      /** Subs */
      subs?: string[];
      /** Predecessors */
      predecessors?: string[];
      /**
       * Milestone
       * @default false
       */
      milestone: boolean;
      /**
       * Depth
       * @default 0
       */
      depth: number;
    };
    /**
     * TaskStatus
     * @enum {string}
     */
    TaskStatus:
      | "todo"
      | "started"
      | "in-progress-50"
      | "in-progress-80"
      | "review"
      | "done"
      | "blocked";
    /** TaskUpdateInput */
    TaskUpdateInput: {
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
      /** Parent */
      parent?: string | null;
      /** Is Phase */
      is_phase?: boolean | null;
      /** Start */
      start?: string | null;
      /** End */
      end?: string | null;
      /** Duration */
      duration?: number | null;
      status?: components["schemas"]["TaskStatus"] | null;
      /** Progress */
      progress?: number | null;
      /** Owner */
      owner?: string | null;
      /** Subs */
      subs?: string[] | null;
      /** Predecessors */
      predecessors?: string[] | null;
      /** Milestone */
      milestone?: boolean | null;
      /** Depth */
      depth?: number | null;
      /**
       * Expected Version
       * @description optimistic locking
       */
      expected_version: number;
    };
    /** User */
    User: {
      /** Id */
      id: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Display Name */
      display_name: string;
      /**
       * Is System Admin
       * @default false
       */
      is_system_admin: boolean;
      /** Avatar Url */
      avatar_url?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  healthz_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  readyz_readyz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  me_api_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  list_projects_api_projects_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"][];
        };
      };
    };
  };
  create_project_api_projects_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectCreateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_project_api_projects__project_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project id */
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_project_api_projects__project_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project id */
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_project_api_projects__project_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project id */
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectUpdateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_tasks_api_projects__project_id__tasks_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project id */
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Task"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_task_api_projects__project_id__tasks_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project id */
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskCreateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Task"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_task_api_projects__project_id__tasks__task_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project id */
        project_id: string;
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Task"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_task_api_projects__project_id__tasks__task_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project id */
        project_id: string;
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_task_api_projects__project_id__tasks__task_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project id */
        project_id: string;
        task_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskUpdateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Task"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_members_api_projects__project_id__members_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project id */
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Membership"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_member_api_projects__project_id__members_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project id */
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MembershipCreateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Membership"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remove_member_api_projects__project_id__members__user_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project id */
        project_id: string;
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_member_api_projects__project_id__members__user_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project id */
        project_id: string;
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MembershipUpdateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Membership"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_comments_api_projects__project_id__tasks__task_id__comments_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project id */
        project_id: string;
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Comment"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_comment_api_projects__project_id__tasks__task_id__comments_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project id */
        project_id: string;
        task_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CommentCreateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Comment"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_comment_api_projects__project_id__tasks__task_id__comments__comment_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project id */
        project_id: string;
        task_id: string;
        comment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_comment_api_projects__project_id__tasks__task_id__comments__comment_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project id */
        project_id: string;
        task_id: string;
        comment_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CommentUpdateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Comment"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_calendars_api_calendar_templates_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CalendarTemplate"][];
        };
      };
    };
  };
  create_calendar_api_calendar_templates_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CalendarCreateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CalendarTemplate"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_calendar_api_calendar_templates__cal_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cal_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CalendarTemplate"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_calendar_api_calendar_templates__cal_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cal_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_calendar_api_calendar_templates__cal_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cal_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CalendarUpdateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CalendarTemplate"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_project_events_api_projects__project_id__events_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path: {
        /** @description Project id */
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Event"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_target_events_api_events_by_target_get: {
    parameters: {
      query: {
        /** @description task | comment | project | membership | calendar */
        type: string;
        id: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Event"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
